### ISSUE TITLE
Dejó de funcionar 

### ISSUE THREAD

**Issue by crak3rjack** [adrianpaniagualeon/iptv-checker#3]
Hace unos días dejó de funcionar, a ver sí por favor puedes verificar y mil gracias.

**Comment by adrianpaniagualeon** [comment]
Buenas tardes, efectivamente el bot (que se ejecutaba en Heroku Free) dejo de funcionar.

El martes espero tenerle otra vez funcionando.

Muchas gracias ☺️

**Comment by adrianpaniagualeon** [comment]
@crak3rjack Ya se encuentra en funcionamiento en un servidor propio. Gracias por avisar
